#kubectl run n1 --image=nginx --port=80 

#kubectl expose pod n1 --port=80 --target-port=80 --name=nsvc --type LoadBalancer

apiVersion: v1
kind: Pod
metadata:
  name: n1
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nsvc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: n1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80